/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Achieves: typeof import('./../components/Achieves/index.vue')['default']
    ArticleCard: typeof import('./../components/Slots/ArticleCard/index.vue')['default']
    ArticleItem: typeof import('./../components/Home/MainFeature/ArticleItem.vue')['default']
    BlogInfo: typeof import('./../components/Edit/BlogInfo/index.vue')['default']
    CardSkelenton: typeof import('./../components/Slots/Skeleton/cardSkelenton.vue')['default']
    Details: typeof import('./../components/Details/index.vue')['default']
    Edit: typeof import('./../components/Edit/index.vue')['default']
    Footer: typeof import('./../components/Footer.vue')['default']
    Header: typeof import('./../components/Header/index.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    Home: typeof import('./../components/Home/index.vue')['default']
    IconCommunity: typeof import('./../components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./../components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../components/icons/IconTooling.vue')['default']
    LeftPopup: typeof import('./../components/Header/LeftPopup/index.vue')['default']
    LeftPopupContent: typeof import('./../components/Header/components/LeftPopupContent.vue')['default']
    Links: typeof import('./../components/Links/index.vue')['default']
    Loading: typeof import('./../components/Business/Loading.vue')['default']
    MainFeature: typeof import('./../components/Home/MainFeature/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tags: typeof import('./../components/Tags/index.vue')['default']
    TheWelcome: typeof import('./../components/TheWelcome.vue')['default']
    TopFeature: typeof import('./../components/Home/TopFeature/index.vue')['default']
    VanCell: typeof import('vant/es')['Cell']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanSidebar: typeof import('vant/es')['Sidebar']
    VanSidebarItem: typeof import('vant/es')['SidebarItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    WelcomeItem: typeof import('./../components/WelcomeItem.vue')['default']
  }
}
